<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>de.richargh.ktkonja</groupId>
    <artifactId>kotlin-kontra-java-core</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <properties>
        <maven.build.timestamp.format>yyyy-MM-dd'T'HH:mm:ss'Z'</maven.build.timestamp.format>
        <kotlin.compiler.incremental>true</kotlin.compiler.incremental>

        <java.version>21</java.version>
        <kotlin.version>2.1.10</kotlin.version>
        <coroutines.version>1.10.1</coroutines.version>
        <junit.version>5.2.0</junit.version>
        <jspecify.version>1.0.0</jspecify.version>
        <error-prone.version>2.18.0</error-prone.version>
        <nullaway.version>0.10.9</nullaway.version>
        <maven-failsafe-plugin.version>3.5.2</maven-failsafe-plugin.version>
        <maven-surefire-plugin.version>3.5.2</maven-surefire-plugin.version>
    </properties>

    <modules>
        <module>feature</module>
        <module>module-usage</module>
        <module>shared-j</module>
        <module>shared-k</module>
    </modules>
</project>